# Generated by Django 4.1.6 on 2023-02-02 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Test1', '0002_remove_post_category'),
        ('Test2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commint',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='commints', to='Test1.post'),
            preserve_default=False,
        ),
    ]
